import type {
  Agent, KpiSummary, ReleaseGate, MotherNode,
  DiagnosticCheck, GatewayRoute, Policy, Alert, User, AuditLog
} from "./contracts";

export const mockKpi: KpiSummary = {
  totalAgents: 24,
  activeAgents: 20,
  errorAgents: 2,
  requestsPerMin: 4821,
  avgLatencyMs: 38,
  totalAlertsOpen: 7,
  uptimePercent: 99.92,
  gatewayHealth: "healthy",
};

export const mockAgents: Agent[] = [
  {
    id: "agt-001",
    name: "inference-worker-alpha",
    version: "v2.4.1",
    status: "active",
    region: "ir-teh-1",
    uptime: "14d 6h 22m",
    lastSeen: new Date(Date.now() - 45000).toISOString(),
    requestsPerMin: 820,
    errorRate: 0.12,
    latencyMs: 32,
    tags: ["inference", "gpu", "primary"],
    endpoint: "https://agt-001.internal.unixsee.io/v1",
    meta: { gpuModel: "A100", vram: "80GB", batchSize: 32 },
  },
  {
    id: "agt-002",
    name: "inference-worker-beta",
    version: "v2.4.1",
    status: "active",
    region: "ir-teh-1",
    uptime: "14d 6h 22m",
    lastSeen: new Date(Date.now() - 62000).toISOString(),
    requestsPerMin: 760,
    errorRate: 0.08,
    latencyMs: 35,
    tags: ["inference", "gpu", "secondary"],
    endpoint: "https://agt-002.internal.unixsee.io/v1",
    meta: { gpuModel: "A100", vram: "80GB", batchSize: 32 },
  },
  {
    id: "agt-003",
    name: "router-gateway-main",
    version: "v1.9.3",
    status: "active",
    region: "ir-teh-1",
    uptime: "30d 14h",
    lastSeen: new Date(Date.now() - 30000).toISOString(),
    requestsPerMin: 4821,
    errorRate: 0.03,
    latencyMs: 8,
    tags: ["router", "gateway", "critical"],
    endpoint: "https://gw.internal.unixsee.io",
    meta: { connections: 248, maxConnections: 10000 },
  },
  {
    id: "agt-004",
    name: "embedding-service",
    version: "v1.2.0",
    status: "active",
    region: "eu-west-1",
    uptime: "7d 3h",
    lastSeen: new Date(Date.now() - 90000).toISOString(),
    requestsPerMin: 320,
    errorRate: 0.05,
    latencyMs: 12,
    tags: ["embedding", "cpu"],
    endpoint: "https://emb.internal.unixsee.io/v1",
    meta: { model: "text-embedding-3-large", dims: 3072 },
  },
  {
    id: "agt-005",
    name: "guardrail-validator",
    version: "v3.1.0",
    status: "degraded",
    region: "ir-teh-2",
    uptime: "2d 11h",
    lastSeen: new Date(Date.now() - 7 * 60000).toISOString(),
    requestsPerMin: 4200,
    errorRate: 2.1,
    latencyMs: 65,
    tags: ["guardrail", "safety", "critical"],
    endpoint: "https://guard.internal.unixsee.io/v1",
    meta: { rulesLoaded: 142, violationsToday: 83 },
  },
  {
    id: "agt-006",
    name: "audit-collector",
    version: "v1.0.8",
    status: "active",
    region: "ir-teh-1",
    uptime: "45d 2h",
    lastSeen: new Date(Date.now() - 55000).toISOString(),
    requestsPerMin: 900,
    errorRate: 0.01,
    latencyMs: 5,
    tags: ["audit", "logging"],
    endpoint: "https://audit.internal.unixsee.io/v1",
    meta: { eventsPerDay: 1290000, retention: "90d" },
  },
  {
    id: "agt-007",
    name: "model-manager-shard2",
    version: "v2.3.7",
    status: "error",
    region: "ir-teh-2",
    uptime: "0d 0h 14m",
    lastSeen: new Date(Date.now() - 15 * 60000).toISOString(),
    requestsPerMin: 0,
    errorRate: 100,
    latencyMs: 0,
    tags: ["model", "management", "error"],
    endpoint: "https://mgr-2.internal.unixsee.io/v1",
    meta: { lastError: "OOM_KILL: process exceeded memory limit", exitCode: 137 },
  },
  {
    id: "agt-008",
    name: "cache-layer-redis",
    version: "v1.5.2",
    status: "active",
    region: "ir-teh-1",
    uptime: "60d 7h",
    lastSeen: new Date(Date.now() - 25000).toISOString(),
    requestsPerMin: 12400,
    errorRate: 0.0,
    latencyMs: 1,
    tags: ["cache", "redis"],
    endpoint: "redis://cache.internal.unixsee.io:6379",
    meta: { hitRate: 94.2, memUsageMB: 3200, keyCount: 428000 },
  },
];

export const mockActiveRelease: ReleaseGate = {
  id: "rel-2026-07-04-001",
  name: "inference-worker v2.5.0",
  version: "v2.5.0",
  stage: "canary",
  progressPercent: 15,
  startedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  estimatedCompletion: new Date(Date.now() + 5 * 3600000).toISOString(),
  gates: [
    { name: "unit-tests", label: "Unit tests", passed: true },
    { name: "integration-tests", label: "Integration tests", passed: true },
    { name: "security-scan", label: "Security scan", passed: true },
    { name: "canary-health", label: "Canary health", passed: true },
    { name: "error-rate-gate", label: "Error rate gate", passed: false },
    { name: "full-rollout", label: "Full rollout", passed: false },
  ],
  canaryMetrics: {
    errorRate: 1.8,
    latencyP99: 142,
    successRate: 98.2,
  },
  approvedBy: "ali.hosseini@unixsee.io",
  notes: "v2.5.0 includes 30% inference throughput improvement and multi-modal model support.",
};

export const mockMotherNodes: MotherNode[] = [
  {
    id: "mth-001",
    name: "mother-core-primary",
    role: "Primary Controller",
    status: "active",
    region: "ir-teh-1",
    connectedAgents: 16,
    syncLag: "12ms",
    cpuPercent: 28,
    memPercent: 61,
    storagePercent: 44,
    lastHeartbeat: new Date(Date.now() - 8000).toISOString(),
  },
  {
    id: "mth-002",
    name: "mother-core-secondary",
    role: "Secondary (Standby)",
    status: "idle",
    region: "ir-teh-2",
    connectedAgents: 8,
    syncLag: "45ms",
    cpuPercent: 12,
    memPercent: 38,
    storagePercent: 44,
    lastHeartbeat: new Date(Date.now() - 10000).toISOString(),
  },
  {
    id: "mth-003",
    name: "mother-edge-eu",
    role: "Edge Relay",
    status: "active",
    region: "eu-west-1",
    connectedAgents: 4,
    syncLag: "210ms",
    cpuPercent: 9,
    memPercent: 22,
    storagePercent: 18,
    lastHeartbeat: new Date(Date.now() - 18000).toISOString(),
  },
];

export const mockDiagnostics: DiagnosticCheck[] = [
  { id: "chk-001", name: "Primary database", component: "database", status: "pass", message: "Connection healthy — 14ms", latencyMs: 14, checkedAt: new Date().toISOString() },
  { id: "chk-002", name: "Redis cache", component: "cache", status: "pass", message: "Healthy — 1ms", latencyMs: 1, checkedAt: new Date().toISOString() },
  { id: "chk-003", name: "API gateway", component: "gateway", status: "pass", message: "Responding normally", latencyMs: 8, checkedAt: new Date().toISOString() },
  { id: "chk-004", name: "Auth service", component: "auth", status: "pass", message: "Tokens valid", latencyMs: 22, checkedAt: new Date().toISOString() },
  { id: "chk-005", name: "Message queue", component: "queue", status: "warn", message: "Processing lag 800ms — below alert threshold", latencyMs: 800, checkedAt: new Date().toISOString() },
  { id: "chk-006", name: "Object storage", component: "storage", status: "pass", message: "Capacity 44% — normal", checkedAt: new Date().toISOString() },
  { id: "chk-007", name: "Model manager shard-2", component: "model-manager", status: "fail", message: "OOM_KILL — process terminated", checkedAt: new Date().toISOString() },
  { id: "chk-008", name: "Guardrail validator", component: "guardrail", status: "warn", message: "Error rate 2.1% — above normal baseline", checkedAt: new Date().toISOString() },
  { id: "chk-009", name: "Notification service", component: "notifications", status: "pass", message: "Delivery successful", latencyMs: 35, checkedAt: new Date().toISOString() },
  { id: "chk-010", name: "TLS / certificate manager", component: "tls", status: "pass", message: "All certificates valid — expires in 89 days", checkedAt: new Date().toISOString() },
];

export const mockGatewayRoutes: GatewayRoute[] = [
  { id: "rt-001", path: "/v1/chat/completions", method: "POST", upstreamAgent: "agt-001", status: "active", rateLimit: 1000, authRequired: true, requestsToday: 284320, avgLatencyMs: 32 },
  { id: "rt-002", path: "/v1/embeddings", method: "POST", upstreamAgent: "agt-004", status: "active", rateLimit: 5000, authRequired: true, requestsToday: 128400, avgLatencyMs: 12 },
  { id: "rt-003", path: "/v1/models", method: "GET", upstreamAgent: "agt-003", status: "active", rateLimit: 100, authRequired: true, requestsToday: 9820, avgLatencyMs: 5 },
  { id: "rt-004", path: "/v1/completions", method: "POST", upstreamAgent: "agt-001", status: "active", rateLimit: 500, authRequired: true, requestsToday: 44100, avgLatencyMs: 41 },
  { id: "rt-005", path: "/v1/moderations", method: "POST", upstreamAgent: "agt-005", status: "active", rateLimit: 2000, authRequired: true, requestsToday: 284320, avgLatencyMs: 65 },
  { id: "rt-006", path: "/internal/health", method: "GET", upstreamAgent: "agt-003", status: "active", rateLimit: 0, authRequired: false, requestsToday: 172800, avgLatencyMs: 3 },
  { id: "rt-007", path: "/v2/chat/completions", method: "POST", upstreamAgent: "agt-002", status: "shadow", rateLimit: 200, authRequired: true, requestsToday: 4210, avgLatencyMs: 35 },
  { id: "rt-008", path: "/v1/images/generations", method: "POST", upstreamAgent: "agt-007", status: "inactive", rateLimit: 100, authRequired: true, requestsToday: 0, avgLatencyMs: 0 },
];

export const mockPolicies: Policy[] = [
  { id: "pol-001", name: "Admin full access", description: "Administrators have unrestricted access to all resources", effect: "allow", resource: "*", conditions: ["role == admin"], priority: 1, enabled: true, createdBy: "system", updatedAt: "2026-01-01T00:00:00Z" },
  { id: "pol-002", name: "Public rate limit", description: "Limit non-admin users to 1000 requests per minute", effect: "deny", resource: "/v1/*", conditions: ["rateLimit > 1000/min", "role != admin"], priority: 10, enabled: true, createdBy: "ali.hosseini@unixsee.io", updatedAt: "2026-06-15T10:00:00Z" },
  { id: "pol-003", name: "Suspicious IP block", description: "Block access from known suspicious IP ranges", effect: "deny", resource: "*", conditions: ["ip in blocklist"], priority: 5, enabled: true, createdBy: "sara.ahmadi@unixsee.io", updatedAt: "2026-06-28T14:30:00Z" },
  { id: "pol-004", name: "Viewer read-only access", description: "Viewers may only access GET endpoints", effect: "allow", resource: "GET /v1/*", conditions: ["role == viewer"], priority: 20, enabled: true, createdBy: "system", updatedAt: "2026-01-01T00:00:00Z" },
  { id: "pol-005", name: "Experimental model quarantine", description: "Experimental models restricted to sandbox environment only", effect: "deny", resource: "/v1/models/experimental/*", conditions: ["env != sandbox"], priority: 8, enabled: false, createdBy: "reza.moradi@unixsee.io", updatedAt: "2026-07-01T09:00:00Z" },
];

export const mockAlerts: Alert[] = [
  { id: "alr-001", title: "OOM Kill on agt-007", severity: "critical", status: "open", source: "agt-007", agentId: "agt-007", message: "model-manager-shard2 process terminated with exit code 137. Memory usage exceeded 16GB limit.", createdAt: new Date(Date.now() - 15 * 60000).toISOString() },
  { id: "alr-002", title: "High error rate on agt-005", severity: "high", status: "acknowledged", source: "agt-005", agentId: "agt-005", message: "guardrail-validator reporting 2.1% error rate — threshold is 1.5%.", createdAt: new Date(Date.now() - 90 * 60000).toISOString(), acknowledgedBy: "sara.ahmadi@unixsee.io" },
  { id: "alr-003", title: "Message queue processing lag", severity: "medium", status: "open", source: "message-queue", message: "Queue processing delay reached 800ms — baseline is 50ms.", createdAt: new Date(Date.now() - 60 * 60000).toISOString() },
  { id: "alr-004", title: "Canary release error rate", severity: "high", status: "open", source: "release-system", message: "v2.5.0 canary deployment reporting 1.8% error rate — error-rate-gate is blocked.", createdAt: new Date(Date.now() - 120 * 60000).toISOString() },
  { id: "alr-005", title: "Suspicious login attempts", severity: "medium", status: "acknowledged", source: "auth-service", message: "23 failed login attempts from IP 185.220.101.x in the past 5 minutes.", createdAt: new Date(Date.now() - 180 * 60000).toISOString(), acknowledgedBy: "ali.hosseini@unixsee.io" },
  { id: "alr-006", title: "Mother EU sync lag elevated", severity: "low", status: "open", source: "mth-003", message: "Sync lag with mother-edge-eu reached 210ms — expected below 100ms.", createdAt: new Date(Date.now() - 110 * 60000).toISOString() },
  { id: "alr-007", title: "Internal SSL certificate expiry notice", severity: "info", status: "resolved", source: "tls-monitor", message: "*.internal.unixsee.io certificate expires in 89 days.", createdAt: new Date(Date.now() - 24 * 3600000).toISOString(), resolvedAt: new Date(Date.now() - 24 * 3600000 + 300000).toISOString() },
];

export const mockUsers: User[] = [
  { id: "usr-001", name: "Ali Hosseini", email: "ali.hosseini@unixsee.io", role: "admin", status: "active", lastLogin: new Date(Date.now() - 3 * 3600000).toISOString(), createdAt: "2024-01-15T00:00:00Z", mfaEnabled: true },
  { id: "usr-002", name: "Sara Ahmadi", email: "sara.ahmadi@unixsee.io", role: "operator", status: "active", lastLogin: new Date(Date.now() - 1 * 3600000).toISOString(), createdAt: "2024-02-20T00:00:00Z", mfaEnabled: true },
  { id: "usr-003", name: "Reza Moradi", email: "reza.moradi@unixsee.io", role: "operator", status: "active", lastLogin: new Date(Date.now() - 16 * 3600000).toISOString(), createdAt: "2024-03-10T00:00:00Z", mfaEnabled: false },
  { id: "usr-004", name: "Niloofar Karimi", email: "niloofar.karimi@unixsee.io", role: "viewer", status: "active", lastLogin: new Date(Date.now() - 40 * 3600000).toISOString(), createdAt: "2024-05-01T00:00:00Z", mfaEnabled: true },
  { id: "usr-005", name: "Mahdi Sadeghi", email: "mahdi.sadeghi@unixsee.io", role: "auditor", status: "active", lastLogin: new Date(Date.now() - 5 * 3600000).toISOString(), createdAt: "2024-06-15T00:00:00Z", mfaEnabled: true },
  { id: "usr-006", name: "Fatemeh Nouri", email: "fatemeh.nouri@unixsee.io", role: "operator", status: "suspended", lastLogin: new Date(Date.now() - 30 * 24 * 3600000).toISOString(), createdAt: "2024-04-01T00:00:00Z", mfaEnabled: false },
  { id: "usr-007", name: "Amir Yazdani", email: "amir.yazdani@unixsee.io", role: "viewer", status: "pending", lastLogin: "", createdAt: new Date(Date.now() - 24 * 3600000).toISOString(), mfaEnabled: false },
];

export const mockAuditLogs: AuditLog[] = [
  { id: "aud-001", action: "deploy", actor: "Ali Hosseini", actorEmail: "ali.hosseini@unixsee.io", resource: "agent", resourceId: "agt-001", description: "Deployed inference-worker-alpha v2.4.1", ipAddress: "10.0.1.5", userAgent: "unixsee-cli/1.2.0", timestamp: new Date(Date.now() - 2 * 3600000).toISOString(), meta: { version: "v2.4.1", region: "ir-teh-1" } },
  { id: "aud-002", action: "policy_change", actor: "Sara Ahmadi", actorEmail: "sara.ahmadi@unixsee.io", resource: "policy", resourceId: "pol-003", description: "Updated suspicious IP block policy conditions", ipAddress: "10.0.1.12", userAgent: "Mozilla/5.0", timestamp: new Date(Date.now() - 6 * 3600000).toISOString(), meta: { field: "conditions", old: "ip in old_blocklist", new: "ip in blocklist" } },
  { id: "aud-003", action: "login", actor: "Ali Hosseini", actorEmail: "ali.hosseini@unixsee.io", resource: "auth", resourceId: "session-abc123", description: "Successful MFA login", ipAddress: "78.39.21.100", userAgent: "Mozilla/5.0", timestamp: new Date(Date.now() - 3 * 3600000).toISOString(), meta: { mfa: true } },
  { id: "aud-004", action: "update", actor: "Reza Moradi", actorEmail: "reza.moradi@unixsee.io", resource: "policy", resourceId: "pol-005", description: "Disabled experimental model quarantine policy", ipAddress: "10.0.1.8", userAgent: "Mozilla/5.0", timestamp: new Date(Date.now() - 24 * 3600000).toISOString(), meta: { field: "enabled", old: true, new: false } },
  { id: "aud-005", action: "delete", actor: "Ali Hosseini", actorEmail: "ali.hosseini@unixsee.io", resource: "user", resourceId: "usr-old-99", description: "Removed stale user account", ipAddress: "10.0.1.5", userAgent: "unixsee-cli/1.2.0", timestamp: new Date(Date.now() - 9 * 24 * 3600000).toISOString(), meta: {} },
  { id: "aud-006", action: "deploy", actor: "ali.hosseini@unixsee.io", actorEmail: "ali.hosseini@unixsee.io", resource: "release", resourceId: "rel-2026-07-04-001", description: "Started canary deployment for v2.5.0", ipAddress: "10.0.1.5", userAgent: "unixsee-cli/1.2.0", timestamp: new Date(Date.now() - 2 * 3600000).toISOString(), meta: { stage: "canary", percent: 15 } },
  { id: "aud-007", action: "create", actor: "Sara Ahmadi", actorEmail: "sara.ahmadi@unixsee.io", resource: "gateway_route", resourceId: "rt-007", description: "Created shadow route for /v2/chat/completions", ipAddress: "10.0.1.12", userAgent: "Mozilla/5.0", timestamp: new Date(Date.now() - 24 * 3600000).toISOString(), meta: { method: "POST", upstream: "agt-002" } },
];
