import type {
  Agent, KpiSummary, ReleaseGate, MotherNode,
  DiagnosticCheck, GatewayRoute, Policy, Alert, User, AuditLog
} from "./contracts";

export const mockKpi: KpiSummary = {
  totalAgents: 24,
  activeAgents: 20,
  errorAgents: 2,
  requestsPerMin: 4821,
  avgLatencyMs: 38,
  totalAlertsOpen: 7,
  uptimePercent: 99.92,
  gatewayHealth: "healthy",
};

export const mockAgents: Agent[] = [
  {
    id: "agt-001",
    name: "inference-worker-alpha",
    version: "v2.4.1",
    status: "active",
    region: "ir-teh-1",
    uptime: "14d 6h 22m",
    lastSeen: "2025-07-02T09:12:00Z",
    requestsPerMin: 820,
    errorRate: 0.12,
    latencyMs: 32,
    tags: ["inference", "gpu", "primary"],
    endpoint: "https://agt-001.internal.unixsee.io/v1",
    meta: { gpuModel: "A100", vram: "80GB", batchSize: 32 },
  },
  {
    id: "agt-002",
    name: "inference-worker-beta",
    version: "v2.4.1",
    status: "active",
    region: "ir-teh-1",
    uptime: "14d 6h 22m",
    lastSeen: "2025-07-02T09:12:00Z",
    requestsPerMin: 760,
    errorRate: 0.08,
    latencyMs: 35,
    tags: ["inference", "gpu", "secondary"],
    endpoint: "https://agt-002.internal.unixsee.io/v1",
    meta: { gpuModel: "A100", vram: "80GB", batchSize: 32 },
  },
  {
    id: "agt-003",
    name: "router-gateway-main",
    version: "v1.9.3",
    status: "active",
    region: "ir-teh-1",
    uptime: "30d 14h",
    lastSeen: "2025-07-02T09:12:00Z",
    requestsPerMin: 4821,
    errorRate: 0.03,
    latencyMs: 8,
    tags: ["router", "gateway", "critical"],
    endpoint: "https://gw.internal.unixsee.io",
    meta: { connections: 248, maxConnections: 10000 },
  },
  {
    id: "agt-004",
    name: "embedding-service",
    version: "v1.2.0",
    status: "active",
    region: "eu-west-1",
    uptime: "7d 3h",
    lastSeen: "2025-07-02T09:11:45Z",
    requestsPerMin: 320,
    errorRate: 0.05,
    latencyMs: 12,
    tags: ["embedding", "cpu"],
    endpoint: "https://emb.internal.unixsee.io/v1",
    meta: { model: "text-embedding-3-large", dims: 3072 },
  },
  {
    id: "agt-005",
    name: "guardrail-validator",
    version: "v3.1.0",
    status: "degraded",
    region: "ir-teh-2",
    uptime: "2d 11h",
    lastSeen: "2025-07-02T09:10:22Z",
    requestsPerMin: 4200,
    errorRate: 2.1,
    latencyMs: 65,
    tags: ["guardrail", "safety", "critical"],
    endpoint: "https://guard.internal.unixsee.io/v1",
    meta: { rulesLoaded: 142, violationsToday: 83 },
  },
  {
    id: "agt-006",
    name: "audit-collector",
    version: "v1.0.8",
    status: "active",
    region: "ir-teh-1",
    uptime: "45d 2h",
    lastSeen: "2025-07-02T09:12:00Z",
    requestsPerMin: 900,
    errorRate: 0.01,
    latencyMs: 5,
    tags: ["audit", "logging"],
    endpoint: "https://audit.internal.unixsee.io/v1",
    meta: { eventsPerDay: 1290000, retention: "90d" },
  },
  {
    id: "agt-007",
    name: "model-manager-shard2",
    version: "v2.3.7",
    status: "error",
    region: "ir-teh-2",
    uptime: "0d 0h 14m",
    lastSeen: "2025-07-02T08:58:00Z",
    requestsPerMin: 0,
    errorRate: 100,
    latencyMs: 0,
    tags: ["model", "management", "error"],
    endpoint: "https://mgr-2.internal.unixsee.io/v1",
    meta: { lastError: "OOM_KILL: process exceeded memory limit", exitCode: 137 },
  },
  {
    id: "agt-008",
    name: "cache-layer-redis",
    version: "v1.5.2",
    status: "active",
    region: "ir-teh-1",
    uptime: "60d 7h",
    lastSeen: "2025-07-02T09:12:00Z",
    requestsPerMin: 12400,
    errorRate: 0.0,
    latencyMs: 1,
    tags: ["cache", "redis"],
    endpoint: "redis://cache.internal.unixsee.io:6379",
    meta: { hitRate: 94.2, memUsageMB: 3200, keyCount: 428000 },
  },
];

export const mockActiveRelease: ReleaseGate = {
  id: "rel-2025-07-02-001",
  name: "inference-worker v2.5.0",
  version: "v2.5.0",
  stage: "canary",
  progressPercent: 15,
  startedAt: "2025-07-02T07:00:00Z",
  estimatedCompletion: "2025-07-02T14:00:00Z",
  gates: [
    { name: "unit-tests", label: "تست‌های یونیت", passed: true },
    { name: "integration-tests", label: "تست‌های یکپارچه‌سازی", passed: true },
    { name: "security-scan", label: "اسکن امنیتی", passed: true },
    { name: "canary-health", label: "سلامت کاناری", passed: true },
    { name: "error-rate-gate", label: "نرخ خطا", passed: false },
    { name: "full-rollout", label: "استقرار کامل", passed: false },
  ],
  canaryMetrics: {
    errorRate: 1.8,
    latencyP99: 142,
    successRate: 98.2,
  },
  approvedBy: "ali.hosseini@unixsee.io",
  notes: "نسخه ۲.۵.۰ شامل بهبود راندمان استنتاج ۳۰٪ و پشتیبانی از مدل‌های چندرسانه‌ای است.",
};

export const mockMotherNodes: MotherNode[] = [
  {
    id: "mth-001",
    name: "mother-core-primary",
    role: "Primary Controller",
    status: "active",
    region: "ir-teh-1",
    connectedAgents: 16,
    syncLag: "12ms",
    cpuPercent: 28,
    memPercent: 61,
    storagePercent: 44,
    lastHeartbeat: "2025-07-02T09:12:00Z",
  },
  {
    id: "mth-002",
    name: "mother-core-secondary",
    role: "Secondary (Standby)",
    status: "idle",
    region: "ir-teh-2",
    connectedAgents: 8,
    syncLag: "45ms",
    cpuPercent: 12,
    memPercent: 38,
    storagePercent: 44,
    lastHeartbeat: "2025-07-02T09:11:58Z",
  },
  {
    id: "mth-003",
    name: "mother-edge-eu",
    role: "Edge Relay",
    status: "active",
    region: "eu-west-1",
    connectedAgents: 4,
    syncLag: "210ms",
    cpuPercent: 9,
    memPercent: 22,
    storagePercent: 18,
    lastHeartbeat: "2025-07-02T09:11:50Z",
  },
];

export const mockDiagnostics: DiagnosticCheck[] = [
  { id: "chk-001", name: "پایگاه داده اصلی", component: "database", status: "pass", message: "اتصال برقرار — ۱۴ms", latencyMs: 14, checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-002", name: "سرویس Redis", component: "cache", status: "pass", message: "سالم — ۱ms", latencyMs: 1, checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-003", name: "گیت‌وی API", component: "gateway", status: "pass", message: "پاسخ‌دهی عادی", latencyMs: 8, checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-004", name: "سرویس احراز هویت", component: "auth", status: "pass", message: "توکن‌ها معتبر", latencyMs: 22, checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-005", name: "صف پیام‌ها", component: "queue", status: "warn", message: "تأخیر ۸۰۰ms — زیر آستانه هشدار", latencyMs: 800, checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-006", name: "ذخیره‌سازی اشیاء", component: "storage", status: "pass", message: "ظرفیت ۴۴٪ — طبیعی", checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-007", name: "مدل‌بان Shard-2", component: "model-manager", status: "fail", message: "OOM_KILL — فرآیند متوقف شده", checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-008", name: "گارد‌ریل Validator", component: "guardrail", status: "warn", message: "نرخ خطا ۲.۱٪ — بالاتر از حد معمول", checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-009", name: "سرویس اعلان‌ها", component: "notifications", status: "pass", message: "ارسال موفق", latencyMs: 35, checkedAt: "2025-07-02T09:12:00Z" },
  { id: "chk-010", name: "TLS/مدیریت گواهی", component: "tls", status: "pass", message: "تمام گواهی‌ها معتبر — انقضا ۸۹ روز دیگر", checkedAt: "2025-07-02T09:12:00Z" },
];

export const mockGatewayRoutes: GatewayRoute[] = [
  { id: "rt-001", path: "/v1/chat/completions", method: "POST", upstreamAgent: "agt-001", status: "active", rateLimit: 1000, authRequired: true, requestsToday: 284320, avgLatencyMs: 32 },
  { id: "rt-002", path: "/v1/embeddings", method: "POST", upstreamAgent: "agt-004", status: "active", rateLimit: 5000, authRequired: true, requestsToday: 128400, avgLatencyMs: 12 },
  { id: "rt-003", path: "/v1/models", method: "GET", upstreamAgent: "agt-003", status: "active", rateLimit: 100, authRequired: true, requestsToday: 9820, avgLatencyMs: 5 },
  { id: "rt-004", path: "/v1/completions", method: "POST", upstreamAgent: "agt-001", status: "active", rateLimit: 500, authRequired: true, requestsToday: 44100, avgLatencyMs: 41 },
  { id: "rt-005", path: "/v1/moderations", method: "POST", upstreamAgent: "agt-005", status: "active", rateLimit: 2000, authRequired: true, requestsToday: 284320, avgLatencyMs: 65 },
  { id: "rt-006", path: "/internal/health", method: "GET", upstreamAgent: "agt-003", status: "active", rateLimit: 0, authRequired: false, requestsToday: 172800, avgLatencyMs: 3 },
  { id: "rt-007", path: "/v2/chat/completions", method: "POST", upstreamAgent: "agt-002", status: "shadow", rateLimit: 200, authRequired: true, requestsToday: 4210, avgLatencyMs: 35 },
  { id: "rt-008", path: "/v1/images/generations", method: "POST", upstreamAgent: "agt-007", status: "inactive", rateLimit: 100, authRequired: true, requestsToday: 0, avgLatencyMs: 0 },
];

export const mockPolicies: Policy[] = [
  { id: "pol-001", name: "دسترسی کامل مدیر", description: "مدیران می‌توانند به تمام منابع دسترسی داشته باشند", effect: "allow", resource: "*", conditions: ["role == admin"], priority: 1, enabled: true, createdBy: "system", updatedAt: "2025-01-01T00:00:00Z" },
  { id: "pol-002", name: "محدودیت نرخ استفاده عمومی", description: "محدودیت ۱۰۰۰ درخواست در دقیقه برای کاربران عمومی", effect: "deny", resource: "/v1/*", conditions: ["rateLimit > 1000/min", "role != admin"], priority: 10, enabled: true, createdBy: "ali.hosseini@unixsee.io", updatedAt: "2025-06-15T10:00:00Z" },
  { id: "pol-003", name: "مسدودیت IP مشکوک", description: "دسترسی از محدوده IP‌های مشکوک را مسدود می‌کند", effect: "deny", resource: "*", conditions: ["ip in blocklist"], priority: 5, enabled: true, createdBy: "sara.ahmadi@unixsee.io", updatedAt: "2025-06-28T14:30:00Z" },
  { id: "pol-004", name: "دسترسی فقط‌خواندنی ناظر", description: "ناظران فقط به endpoint‌های GET دسترسی دارند", effect: "allow", resource: "GET /v1/*", conditions: ["role == viewer"], priority: 20, enabled: true, createdBy: "system", updatedAt: "2025-01-01T00:00:00Z" },
  { id: "pol-005", name: "قرنطینه مدل آزمایشی", description: "مدل‌های آزمایشی فقط در محیط sandbox قابل استفاده هستند", effect: "deny", resource: "/v1/models/experimental/*", conditions: ["env != sandbox"], priority: 8, enabled: false, createdBy: "reza.moradi@unixsee.io", updatedAt: "2025-07-01T09:00:00Z" },
];

export const mockAlerts: Alert[] = [
  { id: "alr-001", title: "OOM Kill روی agt-007", severity: "critical", status: "open", source: "agt-007", agentId: "agt-007", message: "فرآیند model-manager-shard2 با کد خروج ۱۳۷ متوقف شد. حافظه مصرفی از حد مجاز ۱۶GB فراتر رفت.", createdAt: "2025-07-02T08:58:00Z" },
  { id: "alr-002", title: "نرخ خطای بالا در agt-005", severity: "high", status: "acknowledged", source: "agt-005", agentId: "agt-005", message: "guardrail-validator نرخ خطای ۲.۱٪ دارد — آستانه هشدار ۱.۵٪ است.", createdAt: "2025-07-02T07:30:00Z", acknowledgedBy: "sara.ahmadi@unixsee.io" },
  { id: "alr-003", title: "تأخیر صف پیام‌رسانی", severity: "medium", status: "open", source: "message-queue", message: "تأخیر پردازش صف به ۸۰۰ms رسید — معمولاً ۵۰ms است.", createdAt: "2025-07-02T09:00:00Z" },
  { id: "alr-004", title: "نرخ خطای Canary Release", severity: "high", status: "open", source: "release-system", message: "نسخه v2.5.0 در استقرار canary نرخ خطای ۱.۸٪ دارد — gate error-rate-gate بسته است.", createdAt: "2025-07-02T07:45:00Z" },
  { id: "alr-005", title: "تلاش‌های ورود مشکوک", severity: "medium", status: "acknowledged", source: "auth-service", message: "۲۳ تلاش ناموفق ورود از IP 185.220.101.x در ۵ دقیقه گذشته.", createdAt: "2025-07-02T06:15:00Z", acknowledgedBy: "ali.hosseini@unixsee.io" },
  { id: "alr-006", title: "اتصال مادر EU کند شده", severity: "low", status: "open", source: "mth-003", message: "تأخیر sync با mother-edge-eu به ۲۱۰ms رسیده — معمولاً زیر ۱۰۰ms است.", createdAt: "2025-07-02T08:10:00Z" },
  { id: "alr-007", title: "گواهی SSL سرویس داخلی", severity: "info", status: "resolved", source: "tls-monitor", message: "گواهی *.internal.unixsee.io در ۸۹ روز دیگر منقضی می‌شود.", createdAt: "2025-07-01T00:00:00Z", resolvedAt: "2025-07-01T00:05:00Z" },
];

export const mockUsers: User[] = [
  { id: "usr-001", name: "علی حسینی", email: "ali.hosseini@unixsee.io", role: "admin", status: "active", lastLogin: "2025-07-02T08:30:00Z", createdAt: "2024-01-15T00:00:00Z", mfaEnabled: true },
  { id: "usr-002", name: "سارا احمدی", email: "sara.ahmadi@unixsee.io", role: "operator", status: "active", lastLogin: "2025-07-02T09:00:00Z", createdAt: "2024-02-20T00:00:00Z", mfaEnabled: true },
  { id: "usr-003", name: "رضا مرادی", email: "reza.moradi@unixsee.io", role: "operator", status: "active", lastLogin: "2025-07-01T17:45:00Z", createdAt: "2024-03-10T00:00:00Z", mfaEnabled: false },
  { id: "usr-004", name: "نیلوفر کریمی", email: "niloofar.karimi@unixsee.io", role: "viewer", status: "active", lastLogin: "2025-06-30T12:00:00Z", createdAt: "2024-05-01T00:00:00Z", mfaEnabled: true },
  { id: "usr-005", name: "مهدی صادقی", email: "mahdi.sadeghi@unixsee.io", role: "auditor", status: "active", lastLogin: "2025-07-02T07:00:00Z", createdAt: "2024-06-15T00:00:00Z", mfaEnabled: true },
  { id: "usr-006", name: "فاطمه نوری", email: "fatemeh.nouri@unixsee.io", role: "operator", status: "suspended", lastLogin: "2025-06-01T09:00:00Z", createdAt: "2024-04-01T00:00:00Z", mfaEnabled: false },
  { id: "usr-007", name: "امیر یزدانی", email: "amir.yazdani@unixsee.io", role: "viewer", status: "pending", lastLogin: "", createdAt: "2025-07-01T10:00:00Z", mfaEnabled: false },
];

export const mockAuditLogs: AuditLog[] = [
  { id: "aud-001", action: "deploy", actor: "علی حسینی", actorEmail: "ali.hosseini@unixsee.io", resource: "agent", resourceId: "agt-001", description: "استقرار inference-worker-alpha v2.4.1", ipAddress: "10.0.1.5", userAgent: "unixsee-cli/1.2.0", timestamp: "2025-07-02T07:00:00Z", meta: { version: "v2.4.1", region: "ir-teh-1" } },
  { id: "aud-002", action: "policy_change", actor: "سارا احمدی", actorEmail: "sara.ahmadi@unixsee.io", resource: "policy", resourceId: "pol-003", description: "به‌روزرسانی سیاست مسدودیت IP مشکوک", ipAddress: "10.0.1.12", userAgent: "Mozilla/5.0", timestamp: "2025-06-28T14:30:00Z", meta: { field: "conditions", old: "ip in old_blocklist", new: "ip in blocklist" } },
  { id: "aud-003", action: "login", actor: "علی حسینی", actorEmail: "ali.hosseini@unixsee.io", resource: "auth", resourceId: "session-abc123", description: "ورود موفق با MFA", ipAddress: "78.39.21.100", userAgent: "Mozilla/5.0", timestamp: "2025-07-02T08:30:00Z", meta: { mfa: true } },
  { id: "aud-004", action: "update", actor: "رضا مرادی", actorEmail: "reza.moradi@unixsee.io", resource: "policy", resourceId: "pol-005", description: "غیرفعال‌سازی سیاست قرنطینه مدل آزمایشی", ipAddress: "10.0.1.8", userAgent: "Mozilla/5.0", timestamp: "2025-07-01T09:00:00Z", meta: { field: "enabled", old: true, new: false } },
  { id: "aud-005", action: "delete", actor: "علی حسینی", actorEmail: "ali.hosseini@unixsee.io", resource: "user", resourceId: "usr-old-99", description: "حذف حساب کاربری قدیمی", ipAddress: "10.0.1.5", userAgent: "unixsee-cli/1.2.0", timestamp: "2025-06-25T11:00:00Z", meta: {} },
  { id: "aud-006", action: "deploy", actor: "ali.hosseini@unixsee.io", actorEmail: "ali.hosseini@unixsee.io", resource: "release", resourceId: "rel-2025-07-02-001", description: "شروع استقرار canary برای v2.5.0", ipAddress: "10.0.1.5", userAgent: "unixsee-cli/1.2.0", timestamp: "2025-07-02T07:00:00Z", meta: { stage: "canary", percent: 15 } },
  { id: "aud-007", action: "create", actor: "سارا احمدی", actorEmail: "sara.ahmadi@unixsee.io", resource: "gateway_route", resourceId: "rt-007", description: "ایجاد مسیر shadow برای /v2/chat/completions", ipAddress: "10.0.1.12", userAgent: "Mozilla/5.0", timestamp: "2025-07-01T16:00:00Z", meta: { method: "POST", upstream: "agt-002" } },
];
