<?php
// app/config.php

return [
    'app_name' => 'Unixsee Campaign Gateway',
    'debug'    => false,

    // Base URL relative to your domain (adjust this according to your hosting setup)
    // For example, if you place `ux_gateway/public` at `/gateway/`
    // then set '/gateway' here.
    'base_url' => '/ux_gateway/public',

    'admin' => [
        'username' => getenv('UX_ADMIN_USER') ?: 'admin',
        // IMPORTANT: Replace this with a real hash generated by password_hash('YourStrongPassword', PASSWORD_DEFAULT)
        // or set via environment variable UX_ADMIN_PASS_HASH
        'password_hash' => getenv('UX_ADMIN_PASS_HASH') ?: '$2y$10$V0nXQGm8FQwV2uZK9Q2ZzuFf9gWf9GgjGzVb7yIN6kXQZ.Nv2Q2u2',
    ],

    'session' => [
        'name'     => 'ux_gateway_sess',
        'lifetime' => 3600,
    ],

    'database' => [
        'driver' => 'sqlite',
        'path'   => __DIR__ . '/../storage/database.sqlite',
    ],

    'themes' => [
        'default' => [
            'primary_color' => '#6366f1',
            'background'    => 'linear-gradient(135deg, #0f172a, #020617)',
            'card_blur'     => true,
            'dark_mode'     => true,
        ],
        'light' => [
            'primary_color' => '#3b82f6',
            'background'    => '#f9fafb',
            'card_blur'     => false,
            'dark_mode'     => false,
        ],
    ],
    
    'gateway' => [
        // اگر خواستی موقتاً صف را غیرفعال کنی، این را false کن
        'enabled'          => true,

        // حداکثر تعداد کاربر همزمان که اجازه عبور دارند
        'max_active_users' => 15000,

        // مدت زمانی که یک کاربر "داخل" حساب می‌شود (ثانیه)
        'session_lifetime' => 120,
    ],
    'security' => [
        'max_login_attempts' => 5,
        'lock_minutes'       => 15,
        'trusted_ips'        => [],
    ],
];
