<?php
// Sanitized release config. Set admin_password and panel_token before using the admin panel or preview mode.
return array (
  'enabled' => false,
  'mode' => 'maintenance',
  'wp_index' => 'index-wp.php',
  'admin_username' => 'unixsee',
  'admin_password' => '',
  'panel_token' => '',
  'agent_shadow_enabled' => false,
  'agent_shadow_endpoint' => 'http://127.0.0.1:8731/v1/shadow/decision',
  'agent_shadow_timeout_ms' => 80,
  'agent_shadow_log_enabled' => true,
  'agent_shadow_log_file' => 'logs/agent-shadow.log',
  'agent_shadow_send_headers' => false,
  'agent_shadow_send_cookies' => false,
  'agent_shadow_secret' => '',
  'timezone' => 'Asia/Tehran',
  'always_allow_ips' => 
  array (
  ),
  'allowed_ips' => 
  array (
  ),
  'blocked_ips' => 
  array (
  ),
  'max_active_users' => 350,
  'server_cpu_cores' => 1,
  'server_cpu_threads' => 1,
  'server_cpu_freq_ghz' => 0.0,
  'server_cpu_model' => '',
  'server_ram_gb' => 1,
  'server_disk_gb' => 1,
  'session_lifetime' => 300,
  'page_cache_ttl' => 30,
  'bypass_paths' => 
  array (
    0 => '/wc-api/',
    1 => '/checkout/order-received/',
    2 => '/checkout/order-pay/',
    3 => '?wc-ajax=checkout',
    4 => '?wc-ajax=update_order_review',
  ),
  'gateway_scope' => 'site',
  'include_paths' => 
  array (
  ),
  'countdown_target' => '',
  'show_countdown' => false,
  'page_title' => 'کمپین در حال آماده‌سازی است',
  'page_subtitle' => 'به دلیل ترافیک بالا، ورود به سایت به صورت نوبتی انجام می‌شود.',
  'media_url' => '',
  'primary_color' => '#1a72e9',
  'bg_color' => '#050816',
  'theme_css_url' => '',
  'body_font_family' => '',
  'persian_font_file' => 'Estedad-VF.woff2',
  'title_font_size' => '22px',
  'subtitle_font_size' => '14px',
  'custom_html' => '',
  'theme_mode' => 'dark',
  'media_width' => '',
  'media_align' => 'center',
  'media_bg_color' => '#ffffff',
  'media_radius' => '60px',
  'brand_tagline' => 'کنترل هوشمند ترافیک',
  'footer_text' => 'Unixsee Campaign Gateway',
  'enable_glow' => true,
  'glow_color' => '#1a72e9',
  'shadow_style' => 'soft-float',
  'auto_retry_enabled' => true,
  'auto_retry_interval' => 30,
  'retry_button_enabled' => true,
  'retry_button_text' => 'بررسی وضعیت ورود',
  'allow_search_bots' => true,
  'bot_user_agents' => 
  array (
    0 => 'googlebot',
    1 => 'googlebot-image',
    2 => 'googlebot-news',
  ),
  'bot_allow_rules' => 
  array (
    0 => 'ua:googlebot',
    1 => 'ua:googlebot-image',
    2 => 'ua:googlebot-news',
    3 => 'ip:66.249.64.0/19',
    4 => 'ua:Googlebot',
    5 => 'ip:66.249.64.0/19',
    6 => 'ip:64.233.160.0/19',
    7 => 'ip:66.102.0.0/20',
    8 => 'ip:72.14.192.0/18',
    9 => 'ip:209.85.128.0/17',
    10 => 'ip:216.58.192.0/19',
    11 => 'ip:216.239.32.0/19',
    12 => 'ua:TelegramBot',
    13 => 'ip:149.154.160.0/20',
    14 => 'ip:91.108.4.0/22',
    15 => 'ip:91.108.8.0/22',
    16 => 'ip:91.108.56.0/22',
    17 => 'ip:149.154.164.0/22',
    18 => 'ua:Twitterbot',
    19 => 'ip:199.16.156.0/22',
    20 => 'ip:199.59.148.0/22',
    21 => 'ip:199.96.56.0/21',
    22 => 'ip:192.133.76.0/22',
    23 => 'ua:facebookexternalhit',
    24 => 'ip:31.13.24.0/21',
    25 => 'ip:31.13.64.0/18',
    26 => 'ip:45.64.40.0/22',
    27 => 'ip:69.63.176.0/20',
    28 => 'ip:157.240.0.0/17',
    29 => 'ip:173.252.64.0/18',
    30 => 'ip:204.15.20.0/22',
    31 => 'ua:LinkedInBot',
    32 => 'ip:108.174.0.0/20',
    33 => 'ip:100.64.0.0/10',
    34 => 'ip:2620:109:c002::/48',
    35 => 'ua:Applebot',
    36 => 'ip:17.0.0.0/8',
  ),
  'bot_deny_rules' => 
  array (
    0 => '* : /wp-admin/',
    1 => '* : /xmlrpc.php',
  ),
  'bot_scoring_enabled' => true,
  'bot_scoring_use_redis' => false,
  'bot_scoring_log_level' => 1,
  'bot_bad_action' => 'queue',
  'bot_score_storage_ttl_seconds' => 21600,
  'bot_score_initial' => 50,
  'bot_score_good_threshold' => 80,
  'bot_score_bad_threshold' => 25,
  'bot_score_decay_half_life_seconds' => 3600,
  'bot_score_rate_threshold' => 40.0,
  'bot_rate_half_life_seconds' => 4.0,
  'bot_rate_cap_rpm' => 6000.0,
  'bot_score_empty_ua_penalty' => 10,
  'bot_score_suspicious_ua_penalty' => 25,
  'bot_score_verified_search_bot_bonus' => 35,
  'bot_score_fake_search_bot_penalty' => 60,
  'bot_score_rate_penalty_points' => 20,
  'bot_score_suspicious_uas' => 
  array (
  ),
  'bot_dns_validation_enabled' => true,
  'bot_dns_validation_mode' => 'strict',
  'bot_dns_cache_ttl_seconds' => 21600,
  'bot_dns_allowed_domains' => 
  array (
  ),
  'bot_cookie_enabled' => false,
  'bot_cookie_name' => 'ux_b',
  'bot_cookie_ttl_seconds' => 7200,
  'bot_cookie_weight' => 0.28,
  'bot_cookie_signing_key' => '',
  'bot_ml_enabled' => false,
  'bot_ml_php_file' => '',
  'auto_block_enabled' => false,
  'auto_block_mode' => 2,
  'auto_block_target' => 'ip',
  'auto_block_strikes' => 5,
  'auto_block_window_seconds' => 600,
  'auto_block_ttl_seconds' => 3600,
  'auto_block_escalation_ladder_seconds' => 
  array (
    0 => 3600,
    1 => 21600,
    2 => 86400,
  ),
  'auto_block_exempt_verified_bots' => false,
  'ua_bank_enabled' => true,
  'traffic_intel_enabled' => true,
  'traffic_intel_net_sample_interval' => 5,
  'traffic_intel_interface' => 'eno1',
  'traffic_intel_chart_minutes' => 30,
  'gateway_indexable' => false,
  'default_language' => 'fa',
  'available_languages' => 
  array (
    0 => 'fa',
    1 => 'en',
  ),
  'max_login_attempts' => 10,
  'lock_minutes' => 15,
  'rate_limit_per_minute' => 0,
  'rate_limit_sleep_seconds' => 0,
  'redis_enabled' => false,
  'redis_host' => '127.0.0.1',
  'redis_port' => 6379,
  'redis_db' => 0,
  'redis_password' => '',
  'redis_required' => true,
  'redis_required_fail_mode' => 'open',
  'queue_shell_enabled' => true,
  'queue_shell_file' => 'ux_queue_shell.html',
  'queue_check_param' => 'uxwr_check',
  'ticket_cookie_enabled' => true,
  'ticket_cookie_name' => 'uxwr_pass',
  'ticket_cookie_ttl_seconds' => 900,
  'ticket_cookie_bind_ua' => true,
  'ticket_cookie_bind_ip' => false,
  'ticket_secret_file' => '.uxwr_secret.php',
  'analytics_cache_ttl' => 3000,
  'analytics_precompute_enabled' => true,
  'analytics_precompute_interval' => 60,
  'analytics_cache_include_lists' => true,
  'smart_target_cpu' => 60.0,
  'smart_target_mem' => 70.0,
  'smart_target_disk' => 70.0,
  'smart_max_conn_per_user' => 5.0,
  'smart_prediction_enabled' => true,
  'smart_prediction_alpha' => 0.96,
  'smart_log_no_change' => false,
  'latency_smart_enabled' => true,
  'latency_record_enabled' => true,
  'latency_window_seconds' => 60,
  'latency_sample_rate' => 0.05,
  'latency_min_samples' => 30,
  'latency_p95_target_ms' => 900,
  'latency_p95_hard_ms' => 2500,
  'latency_err_rate_high_pct' => 2.0,
  'smart_history_retention_days' => 90,
  'smart_decisions_retention_days' => 90,
  'bot_scoring_persist_sqlite' => true,
  'bot_scoring_persist_sqlite_non_neutral_only' => true,
  'bot_scoring_sqlite_write_interval_seconds' => 300,
  'bot_scoring_sqlite_write_score_delta' => 10,
  'bot_dns_persist_sqlite' => false,
  'bot_block_cache_ttl_seconds' => 300,
  'ua_bank_record_humans' => false,
  'ua_bank_human_sample_rate' => 0.0,
  'redis_prefix' => 'uxgw:',
  'redis_persistent' => true,
  'redis_persistent_id' => 'uxgw',
  'redis_connect_timeout' => 0.5,
  'redis_read_timeout' => 1.0,
  'smart_update_interval_seconds' => 3,
  'smart_modules_auto_enable' => true,
  'smart_modules_enabled' => 
  array (
  ),
  'smart_modules_disabled' => 
  array (
  ),
  'smart_modules_dir' => 'smart_modules',
  'smart_modules_debug' => false,
  'metrics_enabled' => true,
  'metrics_retention_seconds' => 600,
  'live_poll_interval_ms' => 500,
  'log_db_path' => false,
  'storage_fail_mode' => 'open',
  'trusted_proxy_enabled' => false,
  'trusted_proxies' => array (),
  'media_width_desktop' => 40,
  'media_width_mobile' => 40,
  'bot_score_fast_path' => true,
  'bot_score_no_js_penalty' => 0,
  'bot_score_hard_bad_threshold' => 0,
  'bot_score_rate_enabled' => true,
  'bot_score_rate_window' => 4,
  'bot_score_rate_max' => 40,
  'bot_score_missing_cookie_penalty' => 10,
);
